"""postgres baseline with tenancy

Revision ID: 7fb9f43202ba
Revises: 
Create Date: 2026-08-18 21:14:28.061159

Replaces the nine revisions that preceded it. Those were authored against SQLite and
never run anywhere else: Alembic's SQLite path rebuilds tables to emulate ALTER, type
affinity hides width and type mismatches that Postgres enforces, and the chain ended
with a batch_alter_table rebuild of installed_apps that has no meaning here. Rather
than audit nine revisions for a database none of them ever touched, this is the schema
as it should be, created natively. The contract's "V0 is a preview — schema may change
without a migration path; config is portable, history is not" is what makes that the
cheap option, and it stops being available at the first external install.

Row-level security is applied at the end, and is the reason the move to Postgres is
worth making rather than a swap of one store for another.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import app.core.crypto

# revision identifiers, used by Alembic.
revision: str = '7fb9f43202ba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Every table holding customer data. `tenants` is absent because it is the table that
# says which tenants exist, `jamf_patch_titles` because it is the global app corpus —
# public catalogue data, no customer rows — and `alembic_version` because it is
# Alembic's own bookkeeping.
TENANT_SCOPED_TABLES = (
    "account_roles",
    "accounts",
    "api_tokens",
    "auth_identities",
    "destinations",
    "device_extension_attributes",
    "devices",
    "event_outbox",
    "feature_flags",
    "installed_apps",
    "login_attempts",
    "mdm_connections",
    "mdm_sync_state",
    "outbox_deliveries",
    "sessions",
)

# Must match app.core.tenancy.TENANT_GUC. Written out rather than imported so a
# migration that has already run keeps meaning what it meant when it ran.
TENANT_GUC = "looninspect.tenant_id"


def _apply_row_level_security() -> None:
    """Make the tenant boundary the database's rule rather than the application's.

    Three details here are each the difference between this working and this being
    decoration:

    FORCE, not just ENABLE. A table's owner is exempt from its own policies by
    default, and the application role owns every table in this schema because it is
    the role Alembic ran as. Without FORCE, all of this is attached, listed by psql's
    table description, and enforcing nothing.

    `current_setting(...)` without the missing-ok argument. An unbound session raises
    instead of matching zero rows, so code that forgets to name a tenant fails loudly
    rather than looking like "there is no data" — which is the kind of bug that ships.
    Two different errors appear depending on the connection: `unrecognized
    configuration parameter` on one that has never carried a tenant, and `invalid input
    syntax for type uuid: ""` on a pooled one whose transaction-local setting has since
    been rolled back. The second is the one seen in practice; both are a raise.

    WITH CHECK as well as USING. USING filters what a statement can see; WITH CHECK
    governs what it can write. Without it a row could be inserted into, or updated
    into, another tenant — the column default already stamps the session's tenant, and
    this is what stops anything from overriding it.

    Not covered here: a foreign key pointing at another tenant's row. Postgres runs
    referential integrity checks with row security bypassed by design, so a composite
    (tenant_id, id) key on every parent would be needed to close that, at the cost of
    a compound key on fourteen tables. The child row is still forced into the acting
    tenant by the policy below, so the gap is a dangling reference rather than a read
    across the boundary.
    """
    predicate = f"tenant_id = current_setting('{TENANT_GUC}')::uuid"

    for table in TENANT_SCOPED_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            f"USING ({predicate}) WITH CHECK ({predicate})"
        )


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jamf_patch_titles',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('app_name', sa.String(length=255), nullable=True),
    sa.Column('bundle_id', sa.String(length=255), nullable=True),
    sa.Column('current_version', sa.String(length=64), nullable=False),
    sa.Column('last_modified', sa.String(length=64), nullable=False),
    sa.Column('patches', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jamf_patch_titles_bundle_id'), 'jamf_patch_titles', ['bundle_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_kind'), 'tenants', ['kind'], unique=False)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), server_default=sa.text("current_setting('looninspect.tenant_id')::uuid"), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('is_break_glass', sa.Boolean(), nullable=False),
    sa.Column('is_service_account', sa.Boolean(), nullable=False),
    sa.Column('external_source', sa.String(length=32), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_account_tenant_email'),
    sa.UniqueConstraint('tenant_id', 'external_source', 'external_id', name='uq_account_external_identity'),
    sa.UniqueConstraint('tenant_id', 'username', name='uq_account_tenant_username')
    )
    op.create_index(op.f('ix_accounts_email'), 'accounts', ['email'], unique=False)
    op.create_index(op.f('ix_accounts_external_id'), 'accounts', ['external_id'], unique=False)
    op.create_index(op.f('ix_accounts_status'), 'accounts', ['status'], unique=False)
    op.create_index(op.f('ix_accounts_tenant_id'), 'accounts', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_accounts_username'), 'accounts', ['username'], unique=False)
    op.create_table('destinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), server_default=sa.text("current_setting('looninspect.tenant_id')::uuid"), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('auth_type', sa.String(length=16), nullable=False),
    sa.Column('auth_header_name', sa.String(length=255), nullable=True),
    sa.Column('auth_secret_encrypted', app.core.crypto.EncryptedString(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('subscribed_events', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_destinations_tenant_id'), 'destinations', ['tenant_id'], unique=False)
    op.create_table('event_outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), server_default=sa.text("current_setting('looninspect.tenant_id')::uuid"), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('fanned_out', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_outbox_created_at'), 'event_outbox', ['created_at'], unique=False)
    op.create_index(op.f('ix_event_outbox_event_type'), 'event_outbox', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_outbox_fanned_out'), 'event_outbox', ['fanned_out'], unique=False)
    op.create_index(op.f('ix_event_outbox_tenant_id'), 'event_outbox', ['tenant_id'], unique=False)
    op.create_table('feature_flags',
    sa.Column('tenant_id', sa.Uuid(), server_default=sa.text("current_setting('looninspect.tenant_id')::uuid"), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('tenant_id', 'key')
    )
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), server_default=sa.text("current_setting('looninspect.tenant_id')::uuid"), nullable=False),
    sa.Column('identifier', sa.String(length=320), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'identifier', 'ip', name='uq_login_attempt_identifier_ip')
    )
    op.create_index(op.f('ix_login_attempts_identifier'), 'login_attempts', ['identifier'], unique=False)
    op.create_index(op.f('ix_login_attempts_tenant_id'), 'login_attempts', ['tenant_id'], unique=False)
    op.create_table('mdm_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), server_default=sa.text("current_setting('looninspect.tenant_id')::uuid"), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('credentials_encrypted', app.core.crypto.EncryptedString(), nullable=True),
    sa.Column('webhook_secret_encrypted', app.core.crypto.EncryptedString(), nullable=True),
    sa.Column('patch_management_provider', sa.String(length=16), nullable=False),
    sa.Column('loonsecio_license_key_encrypted', app.core.crypto.EncryptedString(), nullable=True),
    sa.Column('loonsecio_data_sharing_enabled', sa.Boolean(), nullable=False),
    sa.Column('user_agent_override', sa.String(length=255), nullable=True),
    sa.Column('capability_devices', sa.Boolean(), nullable=False),
    sa.Column('capability_users', sa.Boolean(), nullable=False),
    sa.Column('capability_webhooks', sa.Boolean(), nullable=False),
    sa.Column('capability_jamf_pro', sa.Boolean(), nullable=False),
    sa.Column('last_successful_auth_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('credentials_rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('credentials_fingerprint', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_mdm_connection_tenant_name')
    )
    op.create_index(op.f('ix_mdm_connections_name'), 'mdm_connections', ['name'], unique=False)
    op.create_index(op.f('ix_mdm_connections_provider'), 'mdm_connections', ['provider'], unique=False)
    op.create_index(op.f('ix_mdm_connections_tenant_id'), 'mdm_connections', ['tenant_id'], unique=False)
    op.create_table('account_roles',
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), server_default=sa.text("current_setting('looninspect.tenant_id')::uuid"), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('granted_by', sa.String(length=36), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('account_id', 'role', 'source')
    )
    op.create_index(op.f('ix_account_roles_tenant_id'), 'account_roles', ['tenant_id'], unique=False)
    op.create_table('api_tokens',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), server_default=sa.text("current_setting('looninspect.tenant_id')::uuid"), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_tokens_account_id'), 'api_tokens', ['account_id'], unique=False)
    op.create_index(op.f('ix_api_tokens_expires_at'), 'api_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_api_tokens_tenant_id'), 'api_tokens', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_api_tokens_token_hash'), 'api_tokens', ['token_hash'], unique=True)
    op.create_table('auth_identities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), server_default=sa.text("current_setting('looninspect.tenant_id')::uuid"), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('secret_hash', sa.String(length=255), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'provider', 'subject', name='uq_auth_identity_provider_subject')
    )
    op.create_index(op.f('ix_auth_identities_account_id'), 'auth_identities', ['account_id'], unique=False)
    op.create_index(op.f('ix_auth_identities_tenant_id'), 'auth_identities', ['tenant_id'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), server_default=sa.text("current_setting('looninspect.tenant_id')::uuid"), nullable=False),
    sa.Column('mdm_connection_id', sa.Integer(), nullable=True),
    sa.Column('mdm_provider', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('serial_number', sa.String(length=64), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_check_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_inventory_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('managed', sa.Boolean(), nullable=True),
    sa.Column('supervised', sa.Boolean(), nullable=True),
    sa.Column('os_version', sa.String(length=64), nullable=True),
    sa.Column('site', sa.String(length=255), nullable=True),
    sa.Column('building', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['mdm_connection_id'], ['mdm_connections.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mdm_connection_id', 'external_id', name='uq_device_connection_external_id')
    )
    op.create_index(op.f('ix_devices_external_id'), 'devices', ['external_id'], unique=False)
    op.create_index(op.f('ix_devices_mdm_connection_id'), 'devices', ['mdm_connection_id'], unique=False)
    op.create_index(op.f('ix_devices_mdm_provider'), 'devices', ['mdm_provider'], unique=False)
    op.create_index(op.f('ix_devices_tenant_id'), 'devices', ['tenant_id'], unique=False)
    op.create_table('mdm_sync_state',
    sa.Column('mdm_connection_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), server_default=sa.text("current_setting('looninspect.tenant_id')::uuid"), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('device_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mdm_connection_id'], ['mdm_connections.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('mdm_connection_id')
    )
    op.create_index(op.f('ix_mdm_sync_state_provider'), 'mdm_sync_state', ['provider'], unique=False)
    op.create_index(op.f('ix_mdm_sync_state_tenant_id'), 'mdm_sync_state', ['tenant_id'], unique=False)
    op.create_table('outbox_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), server_default=sa.text("current_setting('looninspect.tenant_id')::uuid"), nullable=False),
    sa.Column('outbox_event_id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=2000), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ),
    sa.ForeignKeyConstraint(['outbox_event_id'], ['event_outbox.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('outbox_event_id', 'destination_id', name='uq_outbox_delivery_event_destination')
    )
    op.create_index(op.f('ix_outbox_deliveries_destination_id'), 'outbox_deliveries', ['destination_id'], unique=False)
    op.create_index(op.f('ix_outbox_deliveries_next_attempt_at'), 'outbox_deliveries', ['next_attempt_at'], unique=False)
    op.create_index(op.f('ix_outbox_deliveries_outbox_event_id'), 'outbox_deliveries', ['outbox_event_id'], unique=False)
    op.create_index(op.f('ix_outbox_deliveries_status'), 'outbox_deliveries', ['status'], unique=False)
    op.create_index(op.f('ix_outbox_deliveries_tenant_id'), 'outbox_deliveries', ['tenant_id'], unique=False)
    op.create_table('device_extension_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), server_default=sa.text("current_setting('looninspect.tenant_id')::uuid"), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'key', name='uq_device_extension_attribute_key')
    )
    op.create_index(op.f('ix_device_extension_attributes_device_id'), 'device_extension_attributes', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_extension_attributes_key'), 'device_extension_attributes', ['key'], unique=False)
    op.create_index(op.f('ix_device_extension_attributes_tenant_id'), 'device_extension_attributes', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_device_extension_attributes_value'), 'device_extension_attributes', ['value'], unique=False)
    op.create_table('installed_apps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), server_default=sa.text("current_setting('looninspect.tenant_id')::uuid"), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('bundle_id', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('short_version', sa.String(length=64), nullable=True),
    sa.Column('app_hash', sa.String(length=32), nullable=False),
    sa.Column('version_hash', sa.String(length=32), nullable=False),
    sa.Column('is_compliant', sa.Boolean(), nullable=True),
    sa.Column('patch_available', sa.Boolean(), nullable=True),
    sa.Column('patch_available_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_patch_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installed_apps_app_hash'), 'installed_apps', ['app_hash'], unique=False)
    op.create_index(op.f('ix_installed_apps_bundle_id'), 'installed_apps', ['bundle_id'], unique=False)
    op.create_index(op.f('ix_installed_apps_tenant_id'), 'installed_apps', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_installed_apps_version_hash'), 'installed_apps', ['version_hash'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), server_default=sa.text("current_setting('looninspect.tenant_id')::uuid"), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('identity_id', sa.String(length=36), nullable=True),
    sa.Column('auth_method', sa.String(length=32), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('idp_session_id', sa.String(length=255), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['identity_id'], ['auth_identities.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_account_id'), 'sessions', ['account_id'], unique=False)
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_tenant_id'), 'sessions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=True)
    # ### end Alembic commands ###

    # Outside the autogenerated block: Alembic does not model policies, so this is
    # hand-written and stays hand-written. A new tenant-scoped table is not finished
    # until its name is in TENANT_SCOPED_TABLES above.
    _apply_row_level_security()


def downgrade() -> None:
    """Downgrade schema.

    No matching teardown for _apply_row_level_security(): a policy belongs to its
    table and is dropped with it.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_tenant_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_account_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_installed_apps_version_hash'), table_name='installed_apps')
    op.drop_index(op.f('ix_installed_apps_tenant_id'), table_name='installed_apps')
    op.drop_index(op.f('ix_installed_apps_bundle_id'), table_name='installed_apps')
    op.drop_index(op.f('ix_installed_apps_app_hash'), table_name='installed_apps')
    op.drop_table('installed_apps')
    op.drop_index(op.f('ix_device_extension_attributes_value'), table_name='device_extension_attributes')
    op.drop_index(op.f('ix_device_extension_attributes_tenant_id'), table_name='device_extension_attributes')
    op.drop_index(op.f('ix_device_extension_attributes_key'), table_name='device_extension_attributes')
    op.drop_index(op.f('ix_device_extension_attributes_device_id'), table_name='device_extension_attributes')
    op.drop_table('device_extension_attributes')
    op.drop_index(op.f('ix_outbox_deliveries_tenant_id'), table_name='outbox_deliveries')
    op.drop_index(op.f('ix_outbox_deliveries_status'), table_name='outbox_deliveries')
    op.drop_index(op.f('ix_outbox_deliveries_outbox_event_id'), table_name='outbox_deliveries')
    op.drop_index(op.f('ix_outbox_deliveries_next_attempt_at'), table_name='outbox_deliveries')
    op.drop_index(op.f('ix_outbox_deliveries_destination_id'), table_name='outbox_deliveries')
    op.drop_table('outbox_deliveries')
    op.drop_index(op.f('ix_mdm_sync_state_tenant_id'), table_name='mdm_sync_state')
    op.drop_index(op.f('ix_mdm_sync_state_provider'), table_name='mdm_sync_state')
    op.drop_table('mdm_sync_state')
    op.drop_index(op.f('ix_devices_tenant_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_mdm_provider'), table_name='devices')
    op.drop_index(op.f('ix_devices_mdm_connection_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_external_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_auth_identities_tenant_id'), table_name='auth_identities')
    op.drop_index(op.f('ix_auth_identities_account_id'), table_name='auth_identities')
    op.drop_table('auth_identities')
    op.drop_index(op.f('ix_api_tokens_token_hash'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_tenant_id'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_expires_at'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_account_id'), table_name='api_tokens')
    op.drop_table('api_tokens')
    op.drop_index(op.f('ix_account_roles_tenant_id'), table_name='account_roles')
    op.drop_table('account_roles')
    op.drop_index(op.f('ix_mdm_connections_tenant_id'), table_name='mdm_connections')
    op.drop_index(op.f('ix_mdm_connections_provider'), table_name='mdm_connections')
    op.drop_index(op.f('ix_mdm_connections_name'), table_name='mdm_connections')
    op.drop_table('mdm_connections')
    op.drop_index(op.f('ix_login_attempts_tenant_id'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_identifier'), table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_table('feature_flags')
    op.drop_index(op.f('ix_event_outbox_tenant_id'), table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_fanned_out'), table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_event_type'), table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_created_at'), table_name='event_outbox')
    op.drop_table('event_outbox')
    op.drop_index(op.f('ix_destinations_tenant_id'), table_name='destinations')
    op.drop_table('destinations')
    op.drop_index(op.f('ix_accounts_username'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_tenant_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_status'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_external_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_email'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_kind'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_jamf_patch_titles_bundle_id'), table_name='jamf_patch_titles')
    op.drop_table('jamf_patch_titles')
    # ### end Alembic commands ###
