"""connection capabilities and auth health

Revision ID: 80435c84a3d6
Revises: 9e6cf3bebced
Create Date: 2026-08-02 08:28:27.251952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80435c84a3d6'
down_revision: Union[str, Sequence[str], None] = '9e6cf3bebced'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mdm_connections', sa.Column('user_agent_override', sa.String(length=255), nullable=True))
    op.add_column('mdm_connections', sa.Column('capability_devices', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('mdm_connections', sa.Column('capability_users', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('mdm_connections', sa.Column('capability_webhooks', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('mdm_connections', sa.Column('capability_jamf_pro', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('mdm_connections', sa.Column('last_successful_auth_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('mdm_connections', sa.Column('client_secret_rotated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('mdm_connections', sa.Column('client_secret_fingerprint', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mdm_connections', 'client_secret_fingerprint')
    op.drop_column('mdm_connections', 'client_secret_rotated_at')
    op.drop_column('mdm_connections', 'last_successful_auth_at')
    op.drop_column('mdm_connections', 'capability_jamf_pro')
    op.drop_column('mdm_connections', 'capability_webhooks')
    op.drop_column('mdm_connections', 'capability_users')
    op.drop_column('mdm_connections', 'capability_devices')
    op.drop_column('mdm_connections', 'user_agent_override')
    # ### end Alembic commands ###
