"""baseline schema

Revision ID: 9e6cf3bebced
Revises: 
Create Date: 2026-08-01 17:33:17.014116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.core.crypto


# revision identifiers, used by Alembic.
revision: str = '9e6cf3bebced'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mdm_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=True),
    sa.Column('client_secret_encrypted', app.core.crypto.EncryptedString(length=1024), nullable=True),
    sa.Column('api_key_encrypted', app.core.crypto.EncryptedString(length=1024), nullable=True),
    sa.Column('webhook_secret_encrypted', app.core.crypto.EncryptedString(length=1024), nullable=True),
    sa.Column('patch_management_provider', sa.String(length=16), nullable=False),
    sa.Column('loonsecio_license_key_encrypted', app.core.crypto.EncryptedString(length=1024), nullable=True),
    sa.Column('loonsecio_data_sharing_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mdm_connections_name'), 'mdm_connections', ['name'], unique=True)
    op.create_index(op.f('ix_mdm_connections_provider'), 'mdm_connections', ['provider'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mdm_connection_id', sa.Integer(), nullable=True),
    sa.Column('mdm_provider', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('serial_number', sa.String(length=64), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_check_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_inventory_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('managed', sa.Boolean(), nullable=True),
    sa.Column('supervised', sa.Boolean(), nullable=True),
    sa.Column('os_version', sa.String(length=64), nullable=True),
    sa.Column('site', sa.String(length=255), nullable=True),
    sa.Column('building', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['mdm_connection_id'], ['mdm_connections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mdm_connection_id', 'external_id', name='uq_device_connection_external_id')
    )
    op.create_index(op.f('ix_devices_external_id'), 'devices', ['external_id'], unique=False)
    op.create_index(op.f('ix_devices_mdm_connection_id'), 'devices', ['mdm_connection_id'], unique=False)
    op.create_index(op.f('ix_devices_mdm_provider'), 'devices', ['mdm_provider'], unique=False)
    op.create_table('mdm_sync_state',
    sa.Column('mdm_connection_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('device_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mdm_connection_id'], ['mdm_connections.id'], ),
    sa.PrimaryKeyConstraint('mdm_connection_id')
    )
    op.create_index(op.f('ix_mdm_sync_state_provider'), 'mdm_sync_state', ['provider'], unique=False)
    op.create_table('device_extension_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'key', name='uq_device_extension_attribute_key')
    )
    op.create_index(op.f('ix_device_extension_attributes_device_id'), 'device_extension_attributes', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_extension_attributes_key'), 'device_extension_attributes', ['key'], unique=False)
    op.create_index(op.f('ix_device_extension_attributes_value'), 'device_extension_attributes', ['value'], unique=False)
    op.create_table('installed_apps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('bundle_id', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('full_hash', sa.String(length=32), nullable=False),
    sa.Column('is_compliant', sa.Boolean(), nullable=True),
    sa.Column('patch_available', sa.Boolean(), nullable=True),
    sa.Column('patch_available_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_patch_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installed_apps_bundle_id'), 'installed_apps', ['bundle_id'], unique=False)
    op.create_index(op.f('ix_installed_apps_full_hash'), 'installed_apps', ['full_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_installed_apps_full_hash'), table_name='installed_apps')
    op.drop_index(op.f('ix_installed_apps_bundle_id'), table_name='installed_apps')
    op.drop_table('installed_apps')
    op.drop_index(op.f('ix_device_extension_attributes_value'), table_name='device_extension_attributes')
    op.drop_index(op.f('ix_device_extension_attributes_key'), table_name='device_extension_attributes')
    op.drop_index(op.f('ix_device_extension_attributes_device_id'), table_name='device_extension_attributes')
    op.drop_table('device_extension_attributes')
    op.drop_index(op.f('ix_mdm_sync_state_provider'), table_name='mdm_sync_state')
    op.drop_table('mdm_sync_state')
    op.drop_index(op.f('ix_devices_mdm_provider'), table_name='devices')
    op.drop_index(op.f('ix_devices_mdm_connection_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_external_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_mdm_connections_provider'), table_name='mdm_connections')
    op.drop_index(op.f('ix_mdm_connections_name'), table_name='mdm_connections')
    op.drop_table('mdm_connections')
    # ### end Alembic commands ###
