"""generic per-provider credentials

Revision ID: c6e40699d3cd
Revises: 80435c84a3d6
Create Date: 2026-08-02 08:44:04.436445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.core.crypto


# revision identifiers, used by Alembic.
revision: str = 'c6e40699d3cd'
down_revision: Union[str, Sequence[str], None] = '80435c84a3d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Credential storage is being restructured (per-provider JSON blob instead of
    # Jamf-specific columns) — existing connections and everything synced from them
    # are wiped rather than migrated, per explicit instruction.
    op.execute("DELETE FROM installed_apps")
    op.execute("DELETE FROM device_extension_attributes")
    op.execute("DELETE FROM devices")
    op.execute("DELETE FROM mdm_sync_state")
    op.execute("DELETE FROM mdm_connections")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mdm_connections', sa.Column('credentials_encrypted', app.core.crypto.EncryptedString(length=2048), nullable=True))
    op.add_column('mdm_connections', sa.Column('credentials_rotated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('mdm_connections', sa.Column('credentials_fingerprint', sa.String(length=3), nullable=True))
    op.drop_column('mdm_connections', 'client_secret_encrypted')
    op.drop_column('mdm_connections', 'client_id')
    op.drop_column('mdm_connections', 'client_secret_fingerprint')
    op.drop_column('mdm_connections', 'client_secret_rotated_at')
    op.drop_column('mdm_connections', 'api_key_encrypted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mdm_connections', sa.Column('api_key_encrypted', sa.VARCHAR(length=1024), nullable=True))
    op.add_column('mdm_connections', sa.Column('client_secret_rotated_at', sa.DATETIME(), nullable=True))
    op.add_column('mdm_connections', sa.Column('client_secret_fingerprint', sa.VARCHAR(length=3), nullable=True))
    op.add_column('mdm_connections', sa.Column('client_id', sa.VARCHAR(length=255), nullable=True))
    op.add_column('mdm_connections', sa.Column('client_secret_encrypted', sa.VARCHAR(length=1024), nullable=True))
    op.drop_column('mdm_connections', 'credentials_fingerprint')
    op.drop_column('mdm_connections', 'credentials_rotated_at')
    op.drop_column('mdm_connections', 'credentials_encrypted')
    # ### end Alembic commands ###
