"""jamf patch titles catalog

Revision ID: dec3e0c04ac1
Revises: c6e40699d3cd
Create Date: 2026-08-03 05:36:00.067999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dec3e0c04ac1'
down_revision: Union[str, Sequence[str], None] = 'c6e40699d3cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jamf_patch_titles',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('app_name', sa.String(length=255), nullable=True),
    sa.Column('bundle_id', sa.String(length=255), nullable=True),
    sa.Column('current_version', sa.String(length=64), nullable=False),
    sa.Column('last_modified', sa.String(length=64), nullable=False),
    sa.Column('patches', sa.JSON(), nullable=False),
    sa.Column('requirements', sa.JSON(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jamf_patch_titles_bundle_id'), 'jamf_patch_titles', ['bundle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jamf_patch_titles_bundle_id'), table_name='jamf_patch_titles')
    op.drop_table('jamf_patch_titles')
    # ### end Alembic commands ###
